### ISSUE TITLE
Colorado/HDC: Null controls in n3c_control_map file

### ISSUE THREAD

**Issue by mgkahn** [Roeder-OHDSI-Forks/Phenotype_Data_Acquisition#1]
@chrisroederucdenver 
New branch: personal_hacking_hdc
New file query_case_control_HDC.sql with @variable replaced and syntax errors/differences fixed so it executes in HDC.

Results of query attached. I need help with interpretation.

I don't think we can get to the underlying issue using the ResultsDatabase because filtering has already occurred in that data set. I think we need to link back to the source OMOP (for HDC, source OMOP = Kratos). We should probably discuss how to proceed with analysis via Zoom. My calendar is available online.
<img width="1103" alt="image001" src="https://user-images.githubusercontent.com/3923918/181620630-8363405d-5267-4546-97de-10370964eba7.png">

**Comment by chrisroederucdenver** [comment]
I think I understand you as saying that we should be able to do the matching directly in Kratos, using the native(?) person_ids as they are. It's surely more complicated in N3C where they use different or modified ids to avoid issues arising from the potential for duplicated IDs from different sites. Is that what you mean about filtering in the ResultsDatabase?

Just doing the matching, as  the original script does, then counting and showing how the matches played out, in this way tells us something about the Kratos data, while avoiding whatever modification or filtering is going on.

Link to that code 
https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/blob/master/PhenotypeScripts/N3C_phenotype_omop_bigquery.sql

**Comment by mgkahn** [comment]
I think I'm chipping away here. Or going down the wrong rabbit hole.

I always run the phenotype code against an LDS version of Kratos called Kratos_N3C. 
Kratos_N3C has 4,015,103 persons (just FYI Kratos has 4,015,104 persons)

The phenotype code creates two sets of patients: n3c_case_cohort and n3c_control_cohort. The controls are taken from the n3c_pre_cohort, not from the full list of patients **(THIS STATEMENT NEEDS TO BE VALIDATED BY N3C)**  See lines 872-893 where I think this is happening.

If the previous paragraph is correct, the possible issue is that we have 237,685 cases but only 750,241 controls to match on rather than 4M patients. So it could be possible that there are not enough controls to meet all of the match criteria.

If you could confirm that the controls are being pulled from n3c_pre_cohort, then I can pursue the hypothesis that the criteria are too tight for the number of potential controls available in the n3c_pre_cohort table. But I should wait for your response so I'm not chasing ghosts.

**Comment by chrisroederucdenver** [comment]
Michael, I think we verified that we **_are_** pulling from pre_cohort.

**Comment by mgkahn** [comment]
Evidence points to depleting controls for sex for controls across the three partitions by Sex value. Cases are pulled from n3c_case_cohort table. Controls are pulled from n3c_control_cohort table. Query below shows counts for cases (2x for 2-buddies), and controls by sex. **Results show that there are insufficient controls**: Shortfall: 114 (Sex = 0); 29,400 (Sex=8507); 28,083 (Sex=8532). Total number of insufficient controls = 57,597, which matches number of NULL controls in the final control_map table.

<img width="764" alt="image" src="https://user-images.githubusercontent.com/3923918/182467768-f312c64c-2314-4ef8-90a3-3d8c9d5a279a.png">

**Comment by mgkahn** [comment]
@chrisroederucdenver You should share the above query with other N3C sites experiencing similar NULL values in N3C_CONTROL_MAP table to see if this explains the same findings in their data sets.

`with cases as (
  select "Cases" as label, sex, count(person_id)*2 as nrows
  from kratos_n3c_results.n3c_case_cohort
  group by label,sex
), 
controls as (
  select "Controls" as label , sex, count( person_id) as nrows
  from kratos_n3c_results.n3c_control_cohort
  group by label,sex
)
select sex, label, nrows from
 (select sex, label, nrows from cases UNION ALL select sex, label, nrows from controls)
 order by sex
`

**Comment by mgkahn** [comment]
Presented to N3C by @chrisroederucdenver . No further action. Code to remain "as is".
