### ISSUE TITLE
Missing patients N3C cohort table versus Kratos

### ISSUE THREAD

**Issue by mgkahn** [Roeder-OHDSI-Forks/Phenotype_Data_Acquisition#2]
Count of patient ids in N3C cohort table versus count of patients from N3C cohort table that link back to source Kratos.

Observed: 94 pat_ids in N3C (336-242) do not link back to Kratos
Expected: All patients link back

<img width="1206" alt="image001 (1)" src="https://user-images.githubusercontent.com/3923918/181624198-5920c2c6-7274-4eb4-9b63-3cabf583051c.png">

**Comment by chrisroederucdenver** [comment]
You have patients in the cohort table that are not in the person table?! Instinct says show me again with a "distinct" in there.

**Comment by mgkahn** [comment]
Closing this issue. Refreshed data. No "missing" patients when linked to PERSON table. Dropped 16 (662,934 - 662,918) patients when linked to PERSON_X, which includes additional joins in Caboodle to pull additional PHI fields so patients may be lost in Caboodle JOIN.

PERSON_X only used for PPRL.

No action required.

<img width="902" alt="image" src="https://user-images.githubusercontent.com/3923918/182470429-b65f21cd-88e0-425f-a4b0-34152abb3814.png">

**Comment by mgkahn** [comment]
Final analysis with refreshed data points to dropped patients only in PERSON_X table, which includes additional JOINS to Caboodle source tables. PERSON_X only used in PPRL. No action for core N3C work needed.
